name = "05-Digital-Twins"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JUDI = "f3b833dc-6b2e-5b9c-b940-873ed6319979"
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.10"
